int _putchar(char c);
int _printf(const char *format, ...);
int print_number(int n);
unsigned int cbinary(unsigned int n, unsigned int d);
void rev_string(char *s);
int chex(unsigned int n);
int low_hex(unsigned  int n);
int coctal(unsigned int n);
int uprint_number(unsigned int n);
char *pts(void * x);
char *getp(unsigned int x);
